### ISSUE TITLE
当用第三方的npm package，而且这个package包含第三方的nodejs api怎么处理

### ISSUE THREAD

**Issue by bjwulin** [williamnie/umi3.0-electron#1]
用preload或者用window.require，都可以再renderer端使用第三方nodejs api，但是我现在导入的trtc-electron-education是npm pakcage，里面有TRTCCloud是nodejs api，出错，报new TRTCCloud()，这行错。

**Comment by williamnie** [comment]
需要提前在/src/renderer/public/renderer.js 中提前引入，这样试试

**Comment by Twisted928** [comment]
> 需要提前在/src/renderer/public/renderer.js 中提前引入，这样试试

打包之后找不到这个renderer.js是什么原因啊
![image](https://user-images.githubusercontent.com/46923858/122182034-79594880-cebc-11eb-9605-b3529f745975.png)

**Comment by williamnie** [comment]
引入的时候写的相对路径还是绝对路径？

**Comment by Twisted928** [comment]
> 引入的时候写的相对路径还是绝对路径？

相对路径，换了个写法就找到他了
![image](https://user-images.githubusercontent.com/46923858/122186120-487b1280-cec0-11eb-8f53-2a1408d6181b.png)

**Comment by Twisted928** [comment]
> 引入的时候写的相对路径还是绝对路径？

还有个小问题是我自己加了个data.txt在public里，从jsx中通过相对路径找不到
![image](https://user-images.githubusercontent.com/46923858/122186233-6c3e5880-cec0-11eb-8590-8152ec796f06.png)
![image](https://user-images.githubusercontent.com/46923858/122186258-73fdfd00-cec0-11eb-9c6a-b106ff3182e9.png)

**Comment by williamnie** [comment]
> > 引入的时候写的相对路径还是绝对路径？
> 
> 还有个小问题是我自己加了个data.txt在public里，从jsx中通过相对路径找不到
> ![image](https://user-images.githubusercontent.com/46923858/122186233-6c3e5880-cec0-11eb-8590-8152ec796f06.png)
> ![image](https://user-images.githubusercontent.com/46923858/122186258-73fdfd00-cec0-11eb-9c6a-b106ff3182e9.png)

看看此时的根目录是啥，dirname貌似变了

**Comment by Twisted928** [comment]
> > > 引入的时候写的相对路径还是绝对路径？
> > 
> > 
> > 还有个小问题是我自己加了个data.txt在public里，从jsx中通过相对路径找不到
> > ![image](https://user-images.githubusercontent.com/46923858/122186233-6c3e5880-cec0-11eb-8590-8152ec796f06.png)
> > ![image](https://user-images.githubusercontent.com/46923858/122186258-73fdfd00-cec0-11eb-9c6a-b106ff3182e9.png)
> 
> 看看此时的根目录是啥，dirname貌似变了

![image](https://user-images.githubusercontent.com/46923858/122319895-deac4880-cf53-11eb-8509-ab83631633e7.png)
打印出来是上面这样，是为啥呀

**Comment by williamnie** [comment]
打包以后默认的路径会改变，dev和prod的基础路径不一致

**Comment by Twisted928** [comment]
> 打包以后默认的路径会改变，dev和prod的基础路径不一致

那为啥回来的dirname变成了/ ？如果我想访问C:\Program Files\Sample Cabinet\resources\app这个路径下的文件该怎么找

**Comment by williamnie** [comment]
根据环境变量，找到相对位置就好了，区分开来写，

**Comment by Twisted928** [comment]
> 根据环境变量，找到相对位置就好了，区分开来写，

拿到的dirname是个 \ ，这个是相对于那一层啊

**Comment by williamnie** [comment]
最外层的根目录
