### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by JasinYip** [williamnie/umi3.0-electron#2]
感谢分享这个模板！

刚发现一个问题：现在项目拉下来直接跑，是会在 renderer.js 中报 `reuqire is not defined` 的错的，原因是在依赖中使用的新版本 Electron v14 默认会把 `contextIsolation` 设为 `true`，而只有在 `contextIsolation` 为 `false` 时才可以使用 `require`。

**Comment by williamnie** [comment]
是的，我这几天把所有的依赖升级了，还没来得及全部过一遍

**Comment by williamnie** [comment]
现在的reuqire 这块处理貌似有些问题，如果不需要preload，应该不用在docuemnt.ejs内引入render.js
