### ISSUE TITLE
merge is not a function

### ISSUE THREAD

**Issue by JasinYip** [williamnie/umi3.0-electron#4]
在执行 `npm run pack` 的过程中，会报 `merge is not a function`，跟踪进去发现是 build/webpack.main.config.js 和 `build/webpack.main.prod.config.js` 中有这样的一句：

```js
const { merge } = require('webpack-merge');
```

而在我安装到的 webpack-merge 版本 v4.2.2 中，它对外 export 的 merge 函数是直接这样写的：

```js
module.exports = merge;
```

所以我把 webpack 配置中的引用改为就好了：
```js
const merge = require('webpack-merge');
```

**Comment by williamnie** [comment]
这个是我的bug，昨天尝试了webpack5 来编译mainjs，发现有问题，又降级了，结果merge忘记改了

**Comment by JasinYip** [comment]
cool，我本还想再发个 PR 改一下，原来是计划要升级，那我坐等升级了 hhh

**Comment by williamnie** [comment]
已经修复了，你拉下代码，暂时恢复到了webpack4，其实升级到5也没啥必要，毕竟主进程的代码很少，编译很快

**Comment by JasinYip** [comment]
🎉 效率！

**Comment by williamnie** [comment]
https://github.com/bytenode/bytenode 

> 🎉 效率！

https://github.com/bytenode/bytenode 可以看看这个包，将核心代码打包成字节码，保护核心代码，把这个集成进去会更好，或者主要逻辑采用golang等编译型语言开发，用node来调用，这样能保护代码
